
twilio:
  account_sid: AC807e99772a64c14af8503541e5d32e64
  auth_token: 1d757d29b324287b4824b65308b796df
  trial_number: +14752646818

#  jdbc:mysql://localhost:3306/alterna?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kevinpeter0057@gmail.com
    password: kyblkbophqxbcktd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  cors:
    allowed-origins: "*"


#jdbc:mysql://alterna-savings.caznqi4vn7za.eu-north-1.rds.amazonaws.com:3306/alterna_db?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
#  jdbc:mysql://localhost:3306/alterna?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false


  datasource:
    url: jdbc:mysql://localhost:3306/alterna_test?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
    username: root
#    username: admin
#    password: Athena0057




#  datasource:
#    url: jdbc:mysql://alterna-savings.caznqi4vn7za.eu-north-1.rds.amazonaws.com:3306/alterna_db?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
#    username: admin
#    password: Athena0057
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  address: 0.0.0.0